// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD24461EBkFytCLxe84r83ygI6eJEKLz5g',
    appId: '1:1074375494631:web:0997b09fe7599b79b34b42',
    messagingSenderId: '1074375494631',
    projectId: 'app-pokemon-d3ceb',
    authDomain: 'app-pokemon-d3ceb.firebaseapp.com',
    databaseURL: 'https://app-pokemon-d3ceb-default-rtdb.firebaseio.com',
    storageBucket: 'app-pokemon-d3ceb.firebasestorage.app',
    measurementId: 'G-W4Z6Q0CXLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTp5mbrMR2xqTF1ujUyqCDxmI15fhi0E4',
    appId: '1:1074375494631:android:1614e5985f7b270db34b42',
    messagingSenderId: '1074375494631',
    projectId: 'app-pokemon-d3ceb',
    databaseURL: 'https://app-pokemon-d3ceb-default-rtdb.firebaseio.com',
    storageBucket: 'app-pokemon-d3ceb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD24461EBkFytCLxe84r83ygI6eJEKLz5g',
    appId: '1:1074375494631:web:7913811db71c999cb34b42',
    messagingSenderId: '1074375494631',
    projectId: 'app-pokemon-d3ceb',
    authDomain: 'app-pokemon-d3ceb.firebaseapp.com',
    databaseURL: 'https://app-pokemon-d3ceb-default-rtdb.firebaseio.com',
    storageBucket: 'app-pokemon-d3ceb.firebasestorage.app',
    measurementId: 'G-E0CPK59KMB',
  );

}